# Section 1 : Thymeleaf pour l'entité Client

### Liste des clients (GET - Thymeleaf)
GET http://localhost:8080/clients/list
Accept: text/html

### Afficher un client par ID (GET - Thymeleaf)
GET http://localhost:8080/clients/view/1
Accept: text/html

### Afficher le formulaire de création de client (GET - Thymeleaf)
GET http://localhost:8080/clients/create
Accept: text/html

### Créer un nouveau client (POST - Thymeleaf)
POST http://localhost:8080/clients/create
Content-Type: application/x-www-form-urlencoded

name=John+Doe&email=john.doe%40example.com&adresse=123+Main+St&telephoneExploitation=0123456789&ville=Paris&personnelEtFonction=Manager

### Afficher le formulaire de modification d'un client (GET - Thymeleaf)
GET http://localhost:8080/clients/edit/1
Accept: text/html


### Modifier un client existant (POST - Thymeleaf)
POST http://localhost:8080/clients/edit/1
Content-Type: application/x-www-form-urlencoded

name=Jane+Doe&email=jane.doe%40example.com&adresse=456+Elm+St&telephoneExploitation=0987654321&ville=Lyon&personnelEtFonction=Directrice

### Supprimer un client (POST - Thymeleaf)
POST http://localhost:8080/clients/delete/1
Accept: text/html

# Section 2 : Thymeleaf pour l'entité Formule
### Liste des formules (GET - Thymeleaf)
GET http://localhost:8080/formules/list
Accept: text/html

### Voir une formule par ID (GET - Thymeleaf)
GET http://localhost:8080/formules/view/1
Accept: text/html

### Afficher le formulaire de création de formule (GET - Thymeleaf)
GET http://localhost:8080/formules/create
Accept: text/html

## Créer une nouvelle formule (POST - Thymeleaf)
POST http://localhost:8080/formules/create
Content-Type: application/x-www-form-urlencoded

libelle=Formule+Premium&formule=Description+de+la+formule&regle.id=1

### Afficher le formulaire d'édition d'une formule (GET - Thymeleaf)
GET http://localhost:8080/formules/edit/1
Accept: text/html

## Modifier une formule existante (POST - Thymeleaf)
POST http://localhost:8080/formules/edit/1
Content-Type: application/x-www-form-urlencoded

libelle=Formule+Avancée&formule=Nouvelle+description&regle.id=2

## Supprimer une formule (POST - Thymeleaf)
POST http://localhost:8080/formules/delete/1
Accept: text/html


