# Section 1 : API REST pour l'entité Client

### Obtenir tous les clients
GET http://localhost:8080/api/clients
Content-Type: application/json



### Obtenir un client par ID
GET http://localhost:8080/api/clients/4
Content-Type: application/json



### Créer un nouveau client
POST http://localhost:8080/api/clients
Content-Type: application/json

{
  "name": "Client XY",
  "email": "clientXY@example.com",
  "adresse": "123 Rue de la guinguette",
  "ville": "Paris",
  "telephoneExploitation": "0123489659",
  "personnelEtFonction": "Responsable",
  "ramassage1": "Lundi",
  "ramassage2": "Mardi",
  "ramassage3": "Mercredi",
  "ramassage4": "Jeudi",
  "ramassage5": "Vendredi",
  "ramassage6": "Samedi",
  "ramassage7": "Dimanche",
  "envoiparDefaut": "Paris",
  "memoRetourSecurite1": "Mémo 1",
  "memoRetourSecurite2": "Mémo 2"
}



### Mettre à jour un client
PUT http://localhost:8080/api/clients/4
Content-Type: application/json

{
  "id": 4,
  "name": "Updated client",
  "email": "client4@example.com",
  "adresse": "456 Avenue de Lyon",
  "ville": "Lyon",
  "telephoneExploitation": "0987654321",
  "personnelEtFonction": "Directeur",
  "ramassage1": "Lundi",
  "ramassage2": "Mardi",
  "ramassage3": "Mercredi",
  "ramassage4": "Jeudi",
  "ramassage5": "Vendredi",
  "ramassage6": "Samedi",
  "ramassage7": "Dimanche",
  "envoiparDefaut": "Lyon",
  "memoRetourSecurite1": "Updated Mémo 1",
  "memoRetourSecurite2": "Updated Mémo 2"
}

### Supprimer un client
DELETE http://localhost:8080/api/clients/13
Content-Type: application/json




## Section 2 : API REST pour l'entité Formule

### Obtenir toutes les formules
GET http://localhost:8080/api/formules
Content-Type: application/json


### Obtenir une formule par ID
GET http://localhost:8080/api/formules/1
Content-Type: application/json


### Créer une nouvelle formule
POST http://localhost:8080/api/formules
Content-Type: application/json

{
  "libelle": "libelle valise regle AB-v2 client",
  "formule": "test formule  regle AB-v2",
  "regle": {
    "id": 1
  }
}


### Mettre à jour une formule
PUT http://localhost:8080/api/formules/1
Content-Type: application/json

{
  "id": 1,
  "libelle": " updated libelle valise regle client",
  "formule": "test formule exception",
  "regle": {
    "id": 1
  }
}


### Supprimer une formule
DELETE http://localhost:8080/api/formules/9
Content-Type: application/json


## Section 3 : API REST pour l'entité JourFerie

### Obtenir toutes les jours feries
GET http://localhost:8080/api/jourferies
Content-Type: application/json


### Obtenir un jour ferié par ID
GET http://localhost:8080/api/jourferies/20
Content-Type: application/json


### Créer un nouveau jour férié
POST http://localhost:8080/api/jourferies
Content-Type: application/json

{
  "regle": {
    "id": 1
  },
  "joursFerieList": [
    "2024-12-25T00:00:00",
    "2023-01-10T00:00:00"
  ]
}



### Section 4 : API REST pour l'entité livreur
### Obtenir tous les livreurs
GET http://localhost:8080/api/livreurs
Content-Type: application/json


### Obtenir un livreurpar ID
GET http://localhost:8080/api/livreurs/3
Content-Type: application/json


### Créer une nouveau livreur
POST http://localhost:8080/api/livreurs
Content-Type: application/json

{
  "codeLivreur": "AV-5870",
  "motDePasse": "1234",
  "nomLivreur": "Doe",
  "prenomLivreur": "Jogn",
  "numeroCartePro": "DJ.5869",
  "telephonePortable": "0625896595",
  "telephoneKobby": "03254895263",
  "telephoneAlphapage": "0956855896",
  "mouvements": [
    {
      "id": 1,
      "dateHeureMouvement": "2024-11-12T08:30:00",
      "dateRetourPrevue": "2024-11-13T18:00:00",
      "dateSortiePrevue": "2024-11-12T09:00:00"
    },
    {
      "id": 2,
      "dateHeureMouvement": "2024-11-14T10:00:00",
      "dateRetourPrevue": "2024-11-15T19:00:00",
      "dateSortiePrevue": "2024-11-14T11:00:00"
    }
  ]
}


### Mettre à jour un livreur
PUT http://localhost:8080/api/livreurs/3
Content-Type: application/json

{
  "id": 3,
  "codeLivreur": "AV-5890",
  "motDePasse": "1584",
  "nomLivreur": "Doe",
  "prenomLivreur": "Jogn",
  "numeroCartePro": "DJ.5869",
  "telephonePortable": "0625896595",
  "telephoneKobby": "03254895263",
  "telephoneAlphapage": "0956855896",
  "mouvements": [
    {
      "id": 1,
      "dateHeureMouvement": "2024-11-12T08:30:00",
      "dateRetourPrevue": "2024-11-13T18:00:00",
      "dateSortiePrevue": "2024-11-12T09:00:00"
    },
    {
      "id": 2,
      "dateHeureMouvement": "2024-11-14T10:00:00",
      "dateRetourPrevue": "2024-11-15T19:00:00",
      "dateSortiePrevue": "2024-11-14T11:00:00"
    }
  ]
}

### Supprimer un livreur
DELETE http://localhost:8080/api/livreurs/10
Content-Type: application/json

## Section 5 : API REST pour l'entité Mouvement
### Obtenir tous les mouvements
GET http://localhost:8080/api/mouvements
Content-Type: application/json


### Obtenir un mouvement par ID
GET http://localhost:8080/api/mouvements/3
Content-Type: application/json


### Créer un nouveau mouvement
POST http://localhost:8080/api/mouvements
Content-Type: application/json

{
  "dateHeureMouvement": "2024-06-02T10:30:00",
  "statutSortie": "finish",
  "dateSortiePrevue": "2024-10-15T09:00:00",
  "dateRetourPrevue": "2024-11-28T18:00:00",
  "valise": {
    "id": 30
  },
  "livreur": {
    "id": 2
  }
}


### Mettre à jour un mouvement
PUT http://localhost:8080/api/mouvements/3
Content-Type: application/json

{
  "id": 3,
  "dateHeureMouvement": "2024-01-02T10:30:07",
  "statutSortie": "finish",
  "dateSortiePrevue": "2024-10-15T09:00:00",
  "dateRetourPrevue": "2024-12-20T18:00:00",
  "valise": {
    "id": 30
  },
  "livreur": {
    "id": 1
  }
}


### Supprimer un mouvement
DELETE http://localhost:8080/api/mouvement/2
Content-Type: application/json


## Section 6 : API REST pour l'entité Probleme
### Obtenir tous les problèmes
GET http://localhost:8080/api/pb
Accept: application/json

### Obtenir un problème par ID
GET http://localhost:8080/api/pb/2
Accept: application/json


### Créer un nouveau problème
POST http://localhost:8080/api/pb
Content-Type: application/json

{
  "descriptionProbleme": "probleme de taille technique",
  "detailsProbleme": "Détails du probleme avec pour description test",
  "valise": {
    "id": 30
  },
  "client": {
    "id": 4
  }
}


### Mettre à jour un problème
PUT http://localhost:8080/api/pb/2
Content-Type: application/json

{
  "id": 2,
  "descriptionProbleme": "probleme de taille technique",
  "detailsProbleme": "Détails du probleme avec pour description test",
  "valise": {
    "id": 1
  },
  "client": {
    "id": 4
  }
}


### Supprimer un problème
DELETE http://localhost:8080/api/pb/1
Accept: application/json


## Section 7 : API REST pour l'entité Régle
### Obtenir tous les regles
GET http://localhost:8080/api/regles
Accept: application/json


### Obtenir une regle par ID
GET http://localhost:8080/api/regles/4
Accept: application/json


### Créer une nouvelle règle
POST http://localhost:8080/api/regles
Content-Type: application/json

{
  "reglePourSortie": "Test XYv2.2",
  "coderegle": "R45589",
  "dateRegle": "2023-12-12T10:30:00",
  "nombreJours": 450,
  "calculCalendaire": 10,
  "fermeJS1": true,
  "fermeJS2": false,
  "typeEntree": "Normale",
  "nbjsmEntree": 50,
  "formule": {
    "id": 2
  },
  "typeRegle": {
    "id": 2
  }
}



### Mettre à jour une règle
PUT http://localhost:8080/api/regles/4
Content-Type: application/json

{
  "reglePourSortie": "Test  Regle sortieXYv2.2",
  "coderegle": "R45589",
  "dateRegle": "2023-12-12T10:30:00",
  "nombreJours": 450,
  "calculCalendaire": 10,
  "fermeJS1": true,
  "fermeJS2": false,
  "typeEntree": "Normale",
  "nbjsmEntree": 50,
  "formule": {
    "id": 2
  },
  "typeRegle": {
    "id": 2
  }
}


### Supprimer une règle
DELETE http://localhost:8080/api/regles/3
Accept: application/json

## Section 8 : API REST pour l'entité Régle Manuelle
### Obtenir tous les regles manuelles
GET http://localhost:8080/api/regle-manuelle
Accept: application/json


### Obtenir une regle manuelle par ID
GET http://localhost:8080/api/regle-manuelle/5
Accept: application/json


### Créer une nouvelle règle manuelle
POST http://localhost:8080/api/regle-manuelle
Content-Type: application/json

{
  "coderegle": "RWA-VOL 3",
  "reglePourSortie": "Règle de sortie manuelle 3",
  "dateRegle": "2023-10-12T10:30:00",
  "descriptionRegle": "Description de la règle manuelle",
  "createurRegle": "Dutois Jean",
  "formule": {
    "id": 2
  }

}


### Mettre à jour une règle manuelle
PUT http://localhost:8080/api/regle-manuelle/5
Content-Type: application/json

{
  "id": 5,
  "coderegle": "RWA-VOL 3.1",
  "reglePourSortie": "Règle de sortie manuelle 3",
  "dateRegle": "2023-10-12T10:30:00",
  "descriptionRegle": "Description de la règle manuelle",
  "createurRegle": "Dutois Jean",
  "formule": {
    "id": 2
  }

}



### Supprimer une règle manuelle
DELETE http://localhost:8080/api/regle-manuelle/3
Accept: application/json

## Section 9 : API REST pour l'entité Retour Sécurité
### Obtenir tous les retour sécurité
GET http://localhost:8080/api/retourSecurite
Accept: application/json


### Obtenir une retour sécurité par ID
GET http://localhost:8080/api/retourSecurite/5
Accept: application/json


### Créer un nouveau retour sécurité
POST http://localhost:8080/api/retourSecurite
Content-Type: application/json

{
  "numero": 256859,
  "datesecurite": "2024-10-10T10:30:00",
  "cloture": false,
  "dateCloture": "2024-12-12T10:30:00",
  "client": {
    "id": 2
  }

}


### Mettre à jour un retour sécurité
PUT http://localhost:8080/api/retourSecurite/5
Content-Type: application/json

{
  "id": 5,
  "numero": 256785,
  "datesecurite": "2024-10-10T10:30:00",
  "cloture": false,
  "dateCloture": "2024-12-12T10:30:00",
  "client": {
    "id": 1
  }

}



### Supprimer un retour sécurité
DELETE http://localhost:8080/api/retourSecurite/2
Accept: application/json

## Section 10 : API REST pour l'entité Sortie Semaine
### Obtenir tous les Sortie Semaine
GET http://localhost:8080/api/sortieSemaine
Accept: application/json


### Obtenir une Sortie Semaine par ID
GET http://localhost:8080/api/sortieSemaine/3
Accept: application/json

### Créer une nouvelle SortieSemaine
POST http://localhost:8080/api/sortieSemaine
Content-Type: application/json

{
  "dateSortieSemaine": "2024-10-21T18:30:00",
  "regle": {
    "id": 4
  }
}



###

PUT http://localhost:8080/api/sortieSemaine/3
Content-Type: application/json

{
  "id": 3,
  "dateSortieSemaine": "2024-10-21T18:30:00",
  "regle": {
    "id": 4
  }
}



### Supprimer un Sortie Semaine
DELETE http://localhost:8080/api/sortieSemaine/2
Accept: application/json

##Section 11 : API REST pour l'entité Type Regle
### Obtenir tous les Type Regle
GET http://localhost:8080/api/typeRegle
Accept: application/json


###

### Obtenir une Type Regle par ID
GET http://localhost:8080/api/typeRegle/6
Accept: application/json

###
### creer Type Regle
POST http://localhost:8080/api/typeRegle
Content-Type: application/json

{
  "nomTypeRegle": "liste des types de regles",
  "listTypesRegles": []
}



###
###modifier le type de regle

PUT http://localhost:8080/api/typeRegle/6
Content-Type: application/json

{
  "id": 6,
  "nomTypeRegle": "liste de tous les types de regles",
  "listTypesRegles": []
}



###
### Supprimer un Type Regle
DELETE http://localhost:8080/api/typeRegle/4
Accept: application/json

### Section 12 : API REST pour l'entité Type Valise
### Obtenir tous les types de valises
GET http://localhost:8080/api/typeValise
Accept: application/json

###

### Obtenir un type de valise par ID
GET http://localhost:8080/api/typeValise/6
Accept: application/json

###

### Créer un nouveau type de valise
POST http://localhost:8080/api/typeValise
Content-Type: application/json

{
  "proprietaire": "Julien hercourt",
  "description": "Valise XY test",
  "valises": [
  ]
}


###

### Mettre à jour un type de valise
PUT http://localhost:8080/api/typeValise/6
Content-Type: application/json

{
  "id": 6,
  "proprietaire": "Julien Delabille",
  "description": "Valise XY test",
  "valises": [
  ]
}

###

### Supprimer un type de valise
DELETE http://localhost:8080/api/typeValise/3
Accept: application/json

### Section 13 : API REST pour l'entité Valise

### Obtenir toutes les valises
GET http://localhost:8080/api/valise
Accept: application/json

###

### Obtenir une valise par ID
GET http://localhost:8080/api/valise/31
Accept: application/json

###

### Créer une nouvelle valise
POST http://localhost:8080/api/valise
Content-Type: application/json

{
  "description": "Valise client XY",
  "numeroValise": 125895,
  "refClient": "REF-812",
  "sortie": "2025-01-15T10:30:00",
  "dateDernierMouvement": "2024-10-14T09:00:00",
  "dateSortiePrevue": "2024-11-16T09:22:00",
  "dateRetourPrevue": "2024-10-20T18:30:00",
  "dateCreation": "2024-10-10T08:00:00",
  "numeroDujeu": "DU-123",
  "client": {
    "id": 2
  },
  "regle": {
    "id": 2
  },
  "typevalise": {
    "id": 4
  }
}


###

### Mettre à jour une valise
PUT http://localhost:8080/api/valise/31
Content-Type: application/json

{
  "id": 31,
  "description": "Valise client XY12",
  "numeroValise": 125898,
  "refClient": "REF-812",
  "sortie": "2025-01-15T10:30:00",
  "dateDernierMouvement": "2024-10-14T09:00:00",
  "dateSortiePrevue": "2024-11-16T09:22:00",
  "dateRetourPrevue": "2024-10-20T18:30:00",
  "dateCreation": "2024-10-10T08:00:00",
  "numeroDujeu": "DU-123",
  "client": {
    "id": 4
  },
  "regle": {
    "id": 2
  },
  "typevalise": {
    "id": 4
  }
}

###

### Supprimer une valise
DELETE http://localhost:8080/api/valise/1
Accept: application/json

###









